[package]
name = "oxide-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "OxideKit runtime (windowing, input, lifecycle)"

[dependencies]
oxide-compiler.workspace = true
oxide-components.workspace = true
oxide-layout.workspace = true
oxide-render.workspace = true
oxide-text.workspace = true

winit.workspace = true
wgpu.workspace = true
pollster.workspace = true
serde.workspace = true
toml.workspace = true
tracing.workspace = true
anyhow.workspace = true
