[package]
name = "oxide-render"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "OxideKit GPU renderer"

[dependencies]
wgpu.workspace = true
bytemuck = { version = "1.24", features = ["derive"] }
